apiVersion: v1
kind: Template
metadata:
  name: "velocigene-web"
  annotations:
    iconClass: "icon-js"
    description: Openshift template for ReactJS application/service deploying
    template.openshift.io/provider-display-name: EPAM
    template.openshift.io/support-url: https://www.epam.com
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: "velocigene-web"
      labels:
        app: "velocigene-web"
    spec:
      ports:
      - name: "velocigene-web"
        port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: "velocigene-web"
      type: ClusterIP
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: "velocigene-web"
  - apiVersion: v1
    data:
      sit-velocigene-ui-default.conf: |
          server {
              listen       8080;
              server_name  _;

              location / {
                  root   /opt/app-root/src/html;
                  try_files $uri $uri/ /index.html;
              }
              location ~* \.(?:jpg|jpeg|gif|png|js|css|ttf|svg|ico)$ {
                  root   /opt/app-root/src/html;
                  access_log off;
                  log_not_found off;
                  expires max;
                  add_header Cache-Control "public";
              }
              error_page  404              /404.html;
              location = /40x.html {
                  root   /opt/app-root/src/html;
              }
              error_page   500 502 503 504  /50x.html;
              location = /50x.html {
                  root   /opt/app-root/src/html;
              }
          }
    kind: ConfigMap
    metadata:
      name: velocigene-web-nginx.conf
  - apiVersion: v1
    kind: Route
    metadata:
      name: "velocigene"
      annotations:
        description: "Route for velocigene-web application"
        haproxy.router.openshift.io/balance: "roundrobin"
      labels:
        app: "velocigene-web"
    spec:
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      path:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: "velocigene-web"
      wildcardPolicy: None
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: "velocigene-web"
      labels:
        app: "velocigene-web"
    spec:
      replicas: "${{REPLICA_COUNT}}"
      selector:
        app: "velocigene-web"
      strategy:
        activeDeadlineSeconds: 21600
        type: Rolling
        rollingParams:
          failurePolicy: Abort
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
      template:
        metadata:
          labels:
            app: "velocigene-web"
        spec:
          serviceAccountName: "velocigene-web"
          containers:
            - name: "velocigene-web"
              image: "rybkaer/test-web:test"
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
              livenessProbe:
                failureThreshold: 5
                initialDelaySeconds: 20
                periodSeconds: 10
                successThreshold: 1
                httpGet:
                  path: /index.html
                  port: 8080
                timeoutSeconds: 5
              readinessProbe:
                failureThreshold: 5
                initialDelaySeconds: 20
                periodSeconds: 10
                successThreshold: 1
                httpGet:
                  path: /index.html
                  port: 8080
                timeoutSeconds: 5
              resources:
                requests:
                  memory: 512Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /opt/app-root/etc/nginx.conf.d
                  name: nginx-default
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: nginx-default
              configMap:
                defaultMode: 420
                name: velocigene-web-nginx.conf
      triggers:
        - type: ConfigChange
parameters:
  - displayName: Docker registry
    name: REGISTRY
    required: true
    value: rybkaer
  - displayName: Application image name
    name: IMAGE_NAME
    required: true
    value: "velocigene-web"
  - displayName: Application version
    name: APP_VERSION
    required: true
    value: "test"
  - displayName: Current namespace
    name: NAMESPACE
    required: true
    value: "velocigen-web-test"
  - displayName: Replica count
    name: REPLICA_COUNT
    required: true
    value: "2"
  - displayName: Routing Subdomain
    name: SUBDOMAIN
    value: "192.168.99.112.nip.io"
